### PR TITLE
fix(utils): Handle programming languages with spaces

### PR DESCRIPTION
**Pull request by SebaUbuntu**

### CODE REVIEW

**Comment by SebaUbuntu** [comment]
Hi, I have no way to test this, but it should fix https://github.com/senpy-club/api-worker/issues/17

**Comment by SebaUbuntu** [comment]
@Fuwn may I tag you here?

**Review by Fuwn — APPROVED** [review]
Just tested this out and everything seems to work great on my end.

Though, the `urlparse` crate seems to have been abandoned in 2016 and has not been maintained since. The crate is minimal and doesn't seem to pose any threats, so we can keep it, for now.

Looks good to me!

**Comment by SebaUbuntu** [comment]
Mh, it seems it still doesn't work (e.g. https://api.senpy.club/v2/language/Visual%20Basic)
Has this change been deployed?
@Fuwn

**Comment by Fuwn** [comment]
You are totally right... I forgot that I had not enabled/ set up automatic deployments for Cloudflare Workers... Should be up when you read this... 😄

**Comment by SebaUbuntu** [comment]
Yep works fine, thank you

Although with this change I actually caused an API change, now returned links are _properly_ URL encoded (and I just realized they shouldn't be encoded at all since we're returning application/json content)

I fixed it here https://github.com/senpy-club/api-worker/pull/19
@Fuwn

**Pull request merged**
